In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print("test")

2.0.0
test


In [7]:
# Any Information can be represented as Tensors
#Image Shape: [3 (RGB), x, y] (Image of x * y resolution)

In [8]:
# Scalar

scalar = torch.tensor(7)
print(scalar ,",", scalar.ndim ,",", scalar.item())

tensor(7) , 0 , 7


In [9]:
# Matrix

matrix = torch.tensor([[1,2,3],[4,5,6]])
print(matrix ,",", matrix.ndim ,",", matrix.shape )

tensor([[1, 2, 3],
        [4, 5, 6]]) , 2 , torch.Size([2, 3])


In [10]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR ,",", TENSOR.ndim ,",", TENSOR.shape )

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) , 3 , torch.Size([1, 3, 3])


In [11]:
# Random Tensors - torch.rand()
# Start with Random Numbers -> Look at Data -> Update Random Numbers -> (Loop)

random_tensor = torch.rand(5, 2, 2)
print(random_tensor)

# print("Dimension :", random_tensor.ndim)
# print("Shape :", random_tensor.shape)

tensor([[[0.9753, 0.1910],
         [0.6599, 0.2394]],

        [[0.2787, 0.0541],
         [0.1303, 0.8615]],

        [[0.4518, 0.2347],
         [0.4499, 0.2485]],

        [[0.4517, 0.6069],
         [0.5749, 0.3001]],

        [[0.3882, 0.8365],
         [0.7797, 0.3970]]])


In [12]:
# Zeros Tensors - torch.zeros()
# Start with Random Numbers -> Look at Data -> Update Random Numbers -> (Loop)

zeros = torch.zeros(3, 3)
ones = torch.ones(3, 3)

print(zeros,"\n")
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [13]:
# torch.arange()

zero_to_ten1 = torch.arange(start=0, end=10, step=1)
zero_to_ten2 = torch.arange(start=0, end=10, step=2)

print(zero_to_ten1)
print(zero_to_ten2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [14]:
# torch.zeros_like() / torch.ones_like()

ten_zeros = torch.zeros_like(input=zero_to_ten1) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# Tensor Operations

tensor = torch.tensor([1, 2, 3])
print(tensor)
print("\n")
print("tensor * tensor / torch.matmul(tensor, tensor)")
print("Equals:", tensor * tensor)
print("\n")
print("tensor + 10")
print("Equals:", tensor +10)

tensor([1, 2, 3])


tensor * tensor / torch.matmul(tensor, tensor)
Equals: tensor([1, 4, 9])


tensor + 10
Equals: tensor([11, 12, 13])


C:\Users\hyun9\AppData\Local\Temp\ipykernel_29828\335771707.py:7: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3575.)
  print("Equals:", tensor * tensor.T)


In [16]:
# Tensor Datatypes
#    - Datatype: float32, float16, float64 (float.double) ...
#    - Device (CPU, GPU)

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations are recorded 

print(f"Shape of tensor: {float_32_tensor.shape}")
print(f"Datatype of tensor: {float_32_tensor.dtype}")
print(f"Device tensor is stored on: {float_32_tensor.device}") # will default to CPU

Shape of tensor: torch.Size([3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [17]:
# Change Tensor Datatype - ____.type()

float_int_tensor = float_32_tensor.type(torch.int)
float_int_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [18]:
# Tensor Transpose - ___.T

tensorA = torch.tensor([[1,2,3],[4,5,6]], dtype=int)
print(tensorA)
tensorA.T #transpose

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [114]:
# Min, Max, Mean, Sum
tensor = torch.tensor([1,3,2,4,6,5])
tensor.max()

tensor(6)

In [117]:
# ArgMin, ArgMax (Index of min / max)

tensor.argmax()

tensor(4)

In [121]:
# Reshape, Stack, Squeeze
#    - Reshape
#    - Stack
#    - Squeeze

x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [122]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [125]:
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [126]:
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [129]:
#indexing

tensor = torch.rand(5,2,2)
tensor

tensor([[[0.1779, 0.5395],
         [0.1871, 0.6375]],

        [[0.6814, 0.0451],
         [0.8519, 0.6612]],

        [[0.5833, 0.8553],
         [0.4496, 0.2953]],

        [[0.0128, 0.7524],
         [0.3141, 0.7397]],

        [[0.4274, 0.7992],
         [0.0431, 0.5278]]])

In [130]:
tensor[0]

tensor([[0.1779, 0.5395],
        [0.1871, 0.6375]])

In [132]:
tensor[0, 0, 0]

tensor(0.1779)

In [134]:
tensor[:, :, 0]

tensor([[0.1779, 0.1871],
        [0.6814, 0.8519],
        [0.5833, 0.4496],
        [0.0128, 0.3141],
        [0.4274, 0.0431]])

In [135]:
# Import from NumPy - torch.from_numpy()

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [136]:
# Export to Numpy - ____.numpy()

tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Pseudorandomness - torch.manual_seed()

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

In [140]:
# Using GPU - ____.to(device)

# !nvidia-smi
# torch.cuda.is_available()

tensor = torch.tensor([1, 2, 3])

device = "cuda" if torch.cuda.is_available() else "cpu" 
tensor_on_gpu = tensor.to(device)

tensor_on_gpu.device

In [145]:
tensor_on_gpu_2 = torch.tensor([1, 2, 3], device=device)
tensor_on_gpu_2.device

device(type='cuda', index=0)

In [148]:
# Back to CPU (for numpy) - ____.cpu().numpy()

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)